@Wordsy.WebApi_HostAddress = http://localhost:5066

### Create a new word
POST {{Wordsy.WebApi_HostAddress}}/api/words
Content-Type: application/json

{
  "userId": "00000000-0000-0000-0000-000000000001",
  "text": "apple",
  "translation": "яблуко"
}

###

### Get all words for a user
GET {{Wordsy.WebApi_HostAddress}}/api/words?userId=00000000-0000-0000-0000-000000000001
Accept: application/json
