@Wordsy.WebApi_HostAddress = http://localhost:5066

### Create a new word
POST {{Wordsy.WebApi_HostAddress}}/api/words
Content-Type: application/json

{
  "userId": "00000000-0000-0000-0000-000000000001",
  "text": "apple",
  "translation": "яблуко"
}

###

# Optional: Get all words (if implemented later)
GET {{Wordsy.WebApi_HostAddress}}/api/words
Accept: application/json
